server:
  port: 8686
spring:
  profiles:
    active: dev
#  dts:
#    username: xxx
#    password: xxxx
#    sid-name: dtsbvvh9l6w22o8bhm
#    group-name: temp_jinmao_data
#    kafka-broker-url-name: dts-cn-shanghai.aliyuncs.com:18001
#    kafka-topic: xxxx
#    initial-checkpoint-name: 1596440543
#    use-config-checkpoint-name: true
#    subscribe-mode-name: subscribe
#    max-poll-records: 100
#  kafka:
#    bootstrap-servers: xxxx:9093,xxxx:9093,xxxx:9093
##      trust-store-password: KafkaOnsClient
#    producer:
#      security:
#        protocol: SASL_SSL
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    properties:
#      partition: 12
#    template:
#      default-topic: prod_rds
#java:
#  security:
#    auth:
#      login:
#        config: E:/temp/java/kafka_client_jaas.conf                     # 基于阿里云提供的
#        trust-store-location: E:/temp/java/kafka.client.truststore.jks  # 基于阿里云提供参考 : https://help.aliyun.com/document_detail/99958.html?spm=a2c4g.11186623.2.14.4c2a30f0KEj6Av#concept-99958-zh
